app_name: netaiops-webhook
listen_host: 0.0.0.0
listen_port: 18080

defaults:
  vendor: ""
  severity: ""

llm:
  enabled: true
  provider: openai_compatible
  base_url: "http://dd-ai-api.em/v1"
  api_key: "607dHSKdGaRCObFDEf6597D36eE5410bB2Ce17Ef81Fd5e05"
  model: "qwen3-max"
  timeout: 60
  verify_ssl: false
  temperature: 0.2
  max_tokens: 1200

analysis:
  save_prompt: false
  save_result: true
