playbook_id: fortigate_device_ping_abnormal
match:
  vendor: fortigate
  alertname_regex: '^(Ping)$'
execution:
  readonly_only: true
  auto_execute_allowed: true
  max_commands: 5
  commands:
    - "get system status"
    - "get system performance status"
    - "get hardware status"
